# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: ci.yml

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v3
    - run: docker-compose -f docker-compose-build.yaml build --parallel
    - run: docker tag udagram-frontend:local princenuel/udagram-frontend:v3
    - run: docker tag udagram-api-user princenuel/udagram-api-user:v3
    - run: docker tag udagram-api-feed princenuel/udagram-api-feed:v3
    - run: docker tag reverseproxy princenuel/reverseproxy:v3
    - run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin
    - run: docker push princenuel/udagram-frontend:v3
    - run: docker push princenuel/udagram-api-user:v3
    - run: docker push princenuel/udagram-api-feed:v3
    - run: docker push princenuel/reverseproxy:v3